import { images } from "./images";

const fake_datas = [
    {
        _id: 1,
        title: "Ordinateur ACER",
        description: "super ordi",
        categories: ["electronique", "machine", "ordinateur"],
        medias: [images.ok, images.background, images.tshirt],
        started_price: 250000,
        increase_price: 1000,
        increase_suggestion_price: [1, 2, 3],
        reserve_price: 300000,
        expiration_time: "2 jours 5 heures",
        enchere_type: "public",
        enchere_status: "pending",
        delivery_options: "gratuite",
        note: 1.5,
        like: true,
        location: "Sotuba"
    },
    {
        _id: 2,
        title: "Ordinateur MSI",
        description: "super ordi",
        categories: ["electronique", "machine", "gamer"],
        medias: [images.background, images.tshirt, images.ok],
        started_price: 350000,
        increase_price: 5000,
        increase_suggestion_price: [1, 2, 3],
        reserve_price: 400000,
        expiration_time: "5 heures",
        enchere_type: "public",
        enchere_status: "pending",
        delivery_options: "teliman", note: 2, location: "Magnambougou"
    },
    {
        _id: 3,
        title: "Machine à laver",
        description: "super ordi",
        categories: ["electronique", "vêtements"],
        medias: [images.background, images.tshirt, images.ok],
        started_price: 45000,
        increase_price: 1500,
        increase_suggestion_price: [1, 2, 3],
        reserve_price: 60000,
        expiration_time: "3 minutes",
        enchere_type: "public",
        enchere_status: "pending",
        delivery_options: "gratuite", location: "Sikasso",
        note: 5
    },
    {
        _id: 4,
        title: "Voiture A26",
        description: "super voiture",
        categories: ["vehicule"],
        medias: [images.background, images.tshirt, images.ok],
        started_price: 1500000,
        increase_price: 50000,
        increase_suggestion_price: [1, 2, 3],
        reserve_price: 1800000,
        expiration_time: "5 jours",
        enchere_type: "public",
        enchere_status: "pending",
        delivery_options: "gratuite", location: "Kalaban Coura",
        note: 4
    },
    {
        _id: 5,
        title: "Terrain 25x25",
        description: "super voiture",
        categories: ["vehicule"],
        medias: [images.background, images.tshirt, images.ok],
        started_price: 1300000,
        increase_price: 50000,
        increase_suggestion_price: [1, 2, 3],
        reserve_price: 2000000,
        expiration_time: "30 seconds",
        enchere_type: "private",
        enchere_status: "pending",
        delivery_options: "gratuite",
        note: 3.5, like: true, location: "Golf Bko",
    },
    {
        _id: 6,
        title: "Smartphone Samsung M31",
        description: "super phone",
        categories: ["electronique", "mobile"],
        medias: [images.tshirt, images.ok, images.background,],
        started_price: 150000,
        increase_price: 500,
        increase_suggestion_price: [1, 2, 3],
        reserve_price: 200000,
        expiration_time: "1 Semaine",
        enchere_type: "public",
        enchere_status: "pending",
        delivery_options: "gratuite",
        location: "Hamdallaye ACI 2000",
        note: 2
    },

    {
        _id: 7,
        title: "Smartphone Samsung A10",
        description: "super phone",
        categories: ["electronique", "mobile"],
        medias: [images.tshirt, images.ok, images.background,],
        started_price: 150000,
        increase_price: 500,
        increase_suggestion_price: [1, 2, 3],
        reserve_price: 200000,
        expiration_time: "1 Semaine",
        enchere_type: "public",
        enchere_status: "pending",
        delivery_options: "gratuite",
        location: "Hamdallaye ACI 2000",
        note: 2
    },
]

const invited_datas = [
    { _id: 1, name: "Mamadou Diallo", image: images.ok, phone: "+22372662254" },
    { _id: 2, name: "Afou Keita", image: images.ok, phone: "+22388662254" },
    { _id: 3, name: "Akissi Kouadio", image: images.ok, phone: "+22379662254" },
    { _id: 4, name: "Réné Kone", image: images.ok, phone: "74662254" },
    { _id: 5, name: "Kouassi Kouadio", image: images.ok, phone: "+22373662254" },
    { _id: 6, name: "Naomie Kodio", image: images.ok, phone: "+22370662254" },
    { _id: 7, name: "Josias Kodio", image: images.ok, phone: "+22371662254" },
    { _id: 8, name: "Anne Dolo", image: images.ok, phone: "+22378662254" },
    { _id: 9, name: "Cheick Diabaté", image: images.ok, phone: "+22383662254" },
    { _id: 10, name: "Mass Dem", image: images.ok, phone: "+22391662254" },
    { _id: 11, name: "Akz", image: images.ok, phone: "+22392662254" },
    { _id: 12, name: "ok", image: images.ok, phone: "+22392662254" },
]

export { fake_datas, invited_datas }