export const images = {
    logo_icon_image: require("../assets/logo_icon_image.jpeg"),
    logo_dark_content: require("../assets/logo_dark_content.jpeg"),
    logo_white_content: require("../assets/logo_white_content.jpeg"),

    background: require("../assets/background.jpg"),
    plus: require("../assets/plus.png"),

    video_icon_image: require("../assets/video_icon_image.png"),
    user_avatar: require("../assets/avatar.png"),
    ok: require("../assets/ok.jpg"),
    tshirt: require("../assets/tshirt.png"),
    facebook: require("../assets/facebook.png"),
    winner: require("../assets/winner.jpg"),
    alimentaire: require("../assets/alimentaire.jpg"),
    animal: require("../assets/animal.jpg"),
    antiquite: require("../assets/antiquite.jpg"),
    bijou: require("../assets/bijou.jpg"),
    cosmetique: require("../assets/cosmetique.jpg"),
    electromenager: require("../assets/electromenager.jpg"),
    electronique: require("../assets/electronique.jpg"),
    immobilier: require("../assets/immobilier.jpg"),
    jardinage: require("../assets/jardinage.jpg"),
    jeux: require("../assets/jeux.jpg"),
    livre: require("../assets/livre.jpg"),
    loisir: require("../assets/loisir.jpg"),
    medical: require("../assets/medical.jpg"),
    scientifique: require("../assets/scientifique.jpg"),
    sport: require("../assets/sport.jpg"),
    vehicule: require("../assets/vehicule.jpeg"),
    vetement: require("../assets/vetement.jpg"),
}